// Auto-generated by scripts/bump-version.mjs — do not edit directly
export const APP_VERSION = 'v0.1.13';
export const BUILD_NUMBER = '0.1.13';
export const BUILD_TIMESTAMP = '2026-09-02T13:39:53.216Z';
export const GIT_COMMIT = '6fa59a9';
