// Auto-generated by scripts/bump-version.mjs — do not edit directly
export const APP_VERSION = 'v0.1.8';
export const BUILD_NUMBER = '0.1.8';
export const BUILD_TIMESTAMP = '2026-09-02T00:33:45.407Z';
export const GIT_COMMIT = '22658ff';
