import {
  type MaintenanceTemplate,
  generateStandardIntervals,
} from './maintenance-templates';

export const MASTER_VEHICLE_CATALOG: MaintenanceTemplate[] = [
  // ==========================================
  // CHEVROLET (15 Modelos)
  // ==========================================
  {
    id: 'gm-groove-15',
    brand: 'Chevrolet',
    model: 'Groove 1.5',
    generationYears: '2021-2025',
    engineDisplacement: '1.5L DOHC 16V (110 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30', spec: 'Dexos 1 Gen 3 / API SP', capacityLiters: 4.0 },
    sparkPlugs: { type: 'Iridio', spec: 'DENSO IXU22 / Torch K6RIU', intervalKm: 40000 },
    brakeFluid: 'DOT 4',
    coolant: 'OAT Orgánico Rojo 50/50',
    transmissionFluid: 'CVT NS-3 / 75W-90 GL-4 Manual',
    intervals: generateStandardIntervals('5W-30 Dexos 1', 'DENSO IXU22 Iridio'),
  },
  {
    id: 'gm-sail-15',
    brand: 'Chevrolet',
    model: 'Sail 1.5',
    generationYears: '2018-2024',
    engineDisplacement: '1.5L DVVT (109 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30', spec: 'Dexos 1 Gen 2 / API SN', capacityLiters: 3.8 },
    sparkPlugs: { type: 'Cobre / Níquel', spec: 'NGK BKR6E-11', intervalKm: 20000 },
    brakeFluid: 'DOT 4',
    coolant: 'Dex-Cool 50/50',
    intervals: generateStandardIntervals('5W-30', 'NGK BKR6E'),
  },
  {
    id: 'gm-dmax-crdi',
    brand: 'Chevrolet',
    model: 'D-Max 2.5/3.0 CRDI',
    generationYears: '2015-2025',
    engineDisplacement: '2.5L / 3.0L Turbo Diésel Intercooler',
    fuelType: 'diesel',
    engineOil: { viscosity: '15W-40 / 5W-30', spec: 'Dexos 2 / API CK-4 / CJ-4', capacityLiters: 7.5 },
    brakeFluid: 'DOT 4',
    coolant: 'Dex-Cool 50/50 Heavy Duty',
    transmissionFluid: '75W-90 GL-5 / ATF D-Max',
    intervals: generateStandardIntervals('15W-40 Diésel', 'Calentadores Diésel'),
  },
  {
    id: 'gm-tracker-turbo',
    brand: 'Chevrolet',
    model: 'Tracker 1.2 Turbo',
    generationYears: '2021-2025',
    engineDisplacement: '1.2L 3-Cilindros Turbo (130 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'Dexos 1 Gen 3 (Correa bañada en aceite)', capacityLiters: 4.2 },
    sparkPlugs: { type: 'Iridio Turbo', spec: 'GM Genuine Iridium', intervalKm: 40000 },
    brakeFluid: 'DOT 4 Low Viscosity',
    coolant: 'Dex-Cool 50/50',
    intervals: generateStandardIntervals('0W-20 Dexos1 Gen3', 'Iridio Turbo'),
  },
  {
    id: 'gm-aveo-family',
    brand: 'Chevrolet',
    model: 'Aveo Family / Activo 1.5',
    generationYears: '2008-2019',
    engineDisplacement: '1.5L SOHC 8V',
    fuelType: 'gasoline',
    engineOil: { viscosity: '10W-30 / 10W-40', spec: 'API SN / Semi-sintético', capacityLiters: 3.75 },
    sparkPlugs: { type: 'Cobre', spec: 'NGK BPR6EY', intervalKm: 20000 },
    brakeFluid: 'DOT 4',
    coolant: 'Verde / Rojo 50/50',
    intervals: generateStandardIntervals('10W-30', 'NGK BPR6EY'),
  },
  {
    id: 'gm-aveo-emotion',
    brand: 'Chevrolet',
    model: 'Aveo Emotion 1.6',
    generationYears: '2009-2018',
    engineDisplacement: '1.6L DOHC 16V (103 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 10W-30', spec: 'Dexos 1 / API SN', capacityLiters: 3.75 },
    sparkPlugs: { type: 'Cobre / Platino', spec: 'NGK BKR6E-11', intervalKm: 25000 },
    brakeFluid: 'DOT 4',
    coolant: 'Dex-Cool 50/50',
    intervals: generateStandardIntervals('5W-30 Dexos', 'NGK BKR6E-11'),
  },
  {
    id: 'gm-onix-turbo',
    brand: 'Chevrolet',
    model: 'Onix 1.0 Turbo',
    generationYears: '2020-2025',
    engineDisplacement: '1.0L Turbo 3-Cilindros (115 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20', spec: 'Dexos 1 Gen 3 (Aceite estricto para correa húmeda)', capacityLiters: 3.8 },
    sparkPlugs: { type: 'Iridio', spec: 'GM Dexos Iridium', intervalKm: 40000 },
    brakeFluid: 'DOT 4',
    coolant: 'Dex-Cool 50/50',
    intervals: generateStandardIntervals('0W-20 Dexos 1 Gen 3', 'Iridio Genuino'),
  },
  {
    id: 'gm-captiva-turbo',
    brand: 'Chevrolet',
    model: 'Captiva Premier 1.5T',
    generationYears: '2019-2025',
    engineDisplacement: '1.5L Turbo DVVT (147 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30', spec: 'Dexos 1 Gen 3 / API SP', capacityLiters: 4.2 },
    sparkPlugs: { type: 'Iridio Turbo', spec: 'Torch / Denso Iridium', intervalKm: 40000 },
    brakeFluid: 'DOT 4',
    coolant: 'OAT Rojo 50/50',
    intervals: generateStandardIntervals('5W-30 Dexos1', 'Iridio Turbo'),
  },
  {
    id: 'gm-spark-gt',
    brand: 'Chevrolet',
    model: 'Spark GT 1.2',
    generationYears: '2011-2022',
    engineDisplacement: '1.2L S-TEC II DOHC 16V (81 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 10W-30', spec: 'Dexos 1 / API SN', capacityLiters: 3.5 },
    sparkPlugs: { type: 'Cobre / Platino', spec: 'Champion / NGK DCPR8E', intervalKm: 25000 },
    brakeFluid: 'DOT 4',
    coolant: 'Dex-Cool 50/50',
    intervals: generateStandardIntervals('5W-30', 'NGK DCPR8E'),
  },
  {
    id: 'gm-spark-chronos',
    brand: 'Chevrolet',
    model: 'Spark Chronos 1.0',
    generationYears: '2006-2016',
    engineDisplacement: '1.0L SOHC 8V',
    fuelType: 'gasoline',
    engineOil: { viscosity: '10W-30 / 10W-40', spec: 'API SN', capacityLiters: 3.2 },
    sparkPlugs: { type: 'Cobre', spec: 'NGK BPR5EY-11', intervalKm: 20000 },
    brakeFluid: 'DOT 4',
    coolant: 'Verde 50/50',
    intervals: generateStandardIntervals('10W-30', 'NGK BPR5EY'),
  },
  {
    id: 'gm-grand-vitara-sz',
    brand: 'Chevrolet',
    model: 'Grand Vitara SZ 2.0/2.4',
    generationYears: '2008-2019',
    engineDisplacement: '2.0L J20A / 2.4L J24B DOHC',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 10W-40', spec: 'API SN / ILSAC GF-5', capacityLiters: 4.8 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK IFR6J11', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Verde / Azul Suzuki Super Coolant',
    intervals: generateStandardIntervals('5W-30', 'NGK IFR6J11 Iridio'),
  },
  {
    id: 'gm-cruze-18',
    brand: 'Chevrolet',
    model: 'Cruze 1.8 / 1.4T',
    generationYears: '2011-2018',
    engineDisplacement: '1.8L Ecotec / 1.4L Turbo',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30', spec: 'Dexos 1 Gen 2 / Gen 3', capacityLiters: 4.5 },
    sparkPlugs: { type: 'Iridio', spec: 'Champion / AC Delco Iridium', intervalKm: 40000 },
    brakeFluid: 'DOT 4',
    coolant: 'Dex-Cool 50/50',
    intervals: generateStandardIntervals('5W-30 Dexos', 'Iridio AC Delco'),
  },
  {
    id: 'gm-trailblazer-v6',
    brand: 'Chevrolet',
    model: 'Trailblazer 2.8 CTDI / 3.6 V6',
    generationYears: '2013-2024',
    engineDisplacement: '2.8L Duramax Turbo Diésel / 3.6L V6',
    fuelType: 'diesel',
    engineOil: { viscosity: '5W-30 / 15W-40', spec: 'Dexos 2 Diésel', capacityLiters: 6.5 },
    brakeFluid: 'DOT 4',
    coolant: 'Dex-Cool 50/50',
    intervals: generateStandardIntervals('5W-30 Dexos2', 'Duramax Diésel'),
  },
  {
    id: 'gm-s10-max',
    brand: 'Chevrolet',
    model: 'S10 Max 2.0T / 2.4',
    generationYears: '2022-2025',
    engineDisplacement: '2.0L Turbo Diésel / 2.4L Gasolina',
    fuelType: 'diesel',
    engineOil: { viscosity: '5W-30 / 10W-40', spec: 'API CK-4 / CJ-4', capacityLiters: 6.0 },
    brakeFluid: 'DOT 4',
    coolant: 'OAT 50/50',
    intervals: generateStandardIntervals('5W-30 Diésel', 'OEM'),
  },
  {
    id: 'gm-tahoe-v8',
    brand: 'Chevrolet',
    model: 'Tahoe / Suburban 5.3 V8',
    generationYears: '2015-2025',
    engineDisplacement: '5.3L EcoTec3 V8 (355 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20', spec: 'Dexos 1 Gen 3', capacityLiters: 7.6 },
    sparkPlugs: { type: 'Iridio Platino', spec: 'AC Delco 12622561', intervalKm: 60000 },
    brakeFluid: 'DOT 4',
    coolant: 'Dex-Cool 50/50',
    intervals: generateStandardIntervals('0W-20 Dexos 1', 'AC Delco Iridio'),
  },

  // ==========================================
  // TOYOTA (15 Modelos)
  // ==========================================
  {
    id: 'toyota-hilux-diesel',
    brand: 'Toyota',
    model: 'Hilux 2.4 / 2.8 D-4D (1GD/2GD)',
    generationYears: '2016-2025',
    engineDisplacement: '2.4L (2GD-FTV) / 2.8L (1GD-FTV) Turbo Diésel',
    fuelType: 'diesel',
    engineOil: { viscosity: '5W-30 / 15W-40', spec: 'Toyota Genuine Motor Oil / API CJ-4 / ACEA C2', capacityLiters: 7.5 },
    brakeFluid: 'DOT 4 / DOT 3',
    coolant: 'Toyota Super Long Life Coolant (Rosa)',
    transmissionFluid: 'Toyota Gear Oil LV 75W / ATF WS',
    intervals: generateStandardIntervals('5W-30 D-4D', 'Inyectores Common Rail'),
  },
  {
    id: 'toyota-yaris-15',
    brand: 'Toyota',
    model: 'Yaris 1.5 (Sedan & Hatchback)',
    generationYears: '2018-2025',
    engineDisplacement: '1.5L 2NR-FE Dual VVT-i (106 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'API SP / ILSAC GF-6A', capacityLiters: 3.6 },
    sparkPlugs: { type: 'Iridio', spec: 'Denso SC16HR11 / NGK ILKAR7B11', intervalKm: 50000 },
    brakeFluid: 'DOT 4 / DOT 3',
    coolant: 'Toyota Super Long Life Coolant (Rosa)',
    transmissionFluid: 'Toyota CVT Fluid FE / 75W Manual',
    intervals: generateStandardIntervals('0W-20 / 5W-30', 'Denso SC16HR11 Iridio'),
  },
  {
    id: 'toyota-corolla-20',
    brand: 'Toyota',
    model: 'Corolla 2.0 Dynamic Force',
    generationYears: '2020-2025',
    engineDisplacement: '2.0L M20A-FKS (170 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-16 / 0W-20', spec: 'API SP / ILSAC GF-6B', capacityLiters: 4.2 },
    sparkPlugs: { type: 'Iridio Doble Punta', spec: 'Denso FC16HR-Q8', intervalKm: 60000 },
    brakeFluid: 'DOT 4',
    coolant: 'Toyota SLLC Rosa',
    intervals: generateStandardIntervals('0W-20 Toyota', 'Denso Iridio'),
  },
  {
    id: 'toyota-fortuner-diesel',
    brand: 'Toyota',
    model: 'Fortuner 2.8 D-4D 4x4',
    generationYears: '2017-2025',
    engineDisplacement: '2.8L 1GD-FTV Turbo Diésel (201 HP)',
    fuelType: 'diesel',
    engineOil: { viscosity: '5W-30 / 15W-40', spec: 'API CK-4 / ACEA C2', capacityLiters: 7.5 },
    brakeFluid: 'DOT 4',
    coolant: 'Toyota SLLC Rosa',
    intervals: generateStandardIntervals('5W-30 D-4D', 'Diésel 1GD'),
  },
  {
    id: 'toyota-rav4-25',
    brand: 'Toyota',
    model: 'RAV4 2.0 / 2.5 Gasolina & Hybrid',
    generationYears: '2019-2025',
    engineDisplacement: '2.5L Dynamic Force Hybrid / 2.0L M20A',
    fuelType: 'hybrid',
    engineOil: { viscosity: '0W-16 / 0W-20', spec: 'API SP / ILSAC GF-6', capacityLiters: 4.5 },
    sparkPlugs: { type: 'Iridio', spec: 'Denso FC16HR-CY9', intervalKm: 60000 },
    brakeFluid: 'DOT 4',
    coolant: 'Toyota SLLC Rosa',
    intervals: generateStandardIntervals('0W-16 Híbrido', 'Denso Iridio'),
  },
  {
    id: 'toyota-land-cruiser-prado',
    brand: 'Toyota',
    model: 'Land Cruiser Prado 2.8/3.0/4.0',
    generationYears: '2010-2025',
    engineDisplacement: '4.0L 1GR-FE V6 / 3.0L 1KD / 2.8L 1GD Diésel',
    fuelType: 'diesel',
    engineOil: { viscosity: '5W-30 / 15W-40', spec: 'API CK-4 / API SN', capacityLiters: 7.2 },
    sparkPlugs: { type: 'Iridio', spec: 'Denso SK20HR11', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Toyota SLLC Rosa',
    intervals: generateStandardIntervals('5W-30 Prado', 'Denso Iridio'),
  },
  {
    id: 'toyota-land-cruiser-70',
    brand: 'Toyota',
    model: 'Land Cruiser Serie 70 (4.0 V6 / 4.5 V8)',
    generationYears: '2007-2025',
    engineDisplacement: '4.0L 1GR-FE V6 / 4.5L 1VD-FTV V8 Diésel',
    fuelType: 'diesel',
    engineOil: { viscosity: '15W-40 / 5W-30', spec: 'API CI-4 / CK-4 Heavy Duty', capacityLiters: 9.5 },
    brakeFluid: 'DOT 4',
    coolant: 'Toyota LLC Rojo',
    intervals: generateStandardIntervals('15W-40 Heavy Duty', 'Heavy Duty'),
  },
  {
    id: 'toyota-4runner-v6',
    brand: 'Toyota',
    model: '4Runner 4.0 V6',
    generationYears: '2010-2024',
    engineDisplacement: '4.0L 1GR-FE Dual VVT-i V6 (270 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'ILSAC GF-5 / GF-6', capacityLiters: 6.2 },
    sparkPlugs: { type: 'Iridio', spec: 'Denso SK20HR11', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Toyota SLLC Rosa',
    intervals: generateStandardIntervals('0W-20 V6', 'Denso Iridio'),
  },
  {
    id: 'toyota-rush-15',
    brand: 'Toyota',
    model: 'Rush 1.5 7-Pasajeros',
    generationYears: '2018-2024',
    engineDisplacement: '1.5L 2NR-VE Dual VVT-i (103 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 0W-20', spec: 'API SN / SP', capacityLiters: 3.5 },
    sparkPlugs: { type: 'Iridio', spec: 'Denso SC16HR11', intervalKm: 40000 },
    brakeFluid: 'DOT 4',
    coolant: 'Toyota SLLC Rosa',
    intervals: generateStandardIntervals('5W-30', 'Denso Iridio'),
  },
  {
    id: 'toyota-avanza-15',
    brand: 'Toyota',
    model: 'Avanza 1.5',
    generationYears: '2012-2024',
    engineDisplacement: '1.5L 3SZ-VE / 2NR-VE',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 10W-40', spec: 'API SN / SP', capacityLiters: 3.5 },
    sparkPlugs: { type: 'Cobre / Platino', spec: 'Denso K16R-U11', intervalKm: 25000 },
    brakeFluid: 'DOT 4',
    coolant: 'Toyota LLC',
    intervals: generateStandardIntervals('5W-30', 'Denso K16R-U11'),
  },
  {
    id: 'toyota-raize-turbo',
    brand: 'Toyota',
    model: 'Raize 1.0T / 1.2',
    generationYears: '2022-2025',
    engineDisplacement: '1.0L Turbo 1KR-VET / 1.2L WA-VE',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'API SP / ILSAC GF-6', capacityLiters: 3.2 },
    sparkPlugs: { type: 'Iridio', spec: 'Denso SC20HR11', intervalKm: 40000 },
    brakeFluid: 'DOT 4',
    coolant: 'Toyota SLLC Rosa',
    intervals: generateStandardIntervals('0W-20 Turbo', 'Denso Iridio'),
  },
  {
    id: 'toyota-prius-hybrid',
    brand: 'Toyota',
    model: 'Prius 1.8 Hybrid',
    generationYears: '2016-2024',
    engineDisplacement: '1.8L 2ZR-FXE Atkinson Hybrid',
    fuelType: 'hybrid',
    engineOil: { viscosity: '0W-20', spec: 'API SP / ILSAC GF-6', capacityLiters: 4.2 },
    sparkPlugs: { type: 'Iridio', spec: 'Denso SC20HR11', intervalKm: 60000 },
    brakeFluid: 'DOT 4',
    coolant: 'Toyota SLLC Rosa (Doble circuito Inversor/Motor)',
    intervals: generateStandardIntervals('0W-20 Híbrido', 'Denso Iridio'),
  },
  {
    id: 'toyota-hiace-diesel',
    brand: 'Toyota',
    model: 'Hiace 2.8 / 3.0 D-4D',
    generationYears: '2012-2025',
    engineDisplacement: '2.8L 1GD / 3.0L 1KD Turbo Diésel',
    fuelType: 'diesel',
    engineOil: { viscosity: '5W-30 / 15W-40', spec: 'API CJ-4 / CK-4', capacityLiters: 7.5 },
    brakeFluid: 'DOT 4',
    coolant: 'Toyota SLLC Rosa',
    intervals: generateStandardIntervals('15W-40 Diésel', 'D-4D'),
  },
  {
    id: 'toyota-corolla-cross',
    brand: 'Toyota',
    model: 'Corolla Cross 2.0 / 1.8H',
    generationYears: '2021-2025',
    engineDisplacement: '2.0L M20A Gasolina / 1.8L Híbrido',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20', spec: 'API SP / ILSAC GF-6', capacityLiters: 4.2 },
    sparkPlugs: { type: 'Iridio', spec: 'Denso FC16HR-Q8', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Toyota SLLC Rosa',
    intervals: generateStandardIntervals('0W-20', 'Denso Iridio'),
  },
  {
    id: 'toyota-tacoma-v6',
    brand: 'Toyota',
    model: 'Tacoma 3.5 V6 / 2.7',
    generationYears: '2016-2024',
    engineDisplacement: '3.5L 2GR-FKS V6 (278 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20', spec: 'API SP / ILSAC GF-6', capacityLiters: 5.9 },
    sparkPlugs: { type: 'Iridio', spec: 'Denso FK20HBR8', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Toyota SLLC Rosa',
    intervals: generateStandardIntervals('0W-20', 'Denso FK20HBR8'),
  },

  // ==========================================
  // KIA (12 Modelos)
  // ==========================================
  {
    id: 'kia-sportage-r',
    brand: 'Kia',
    model: 'Sportage R / Active 2.0',
    generationYears: '2011-2022',
    engineDisplacement: '2.0L Nu / Beta II DOHC 16V',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 10W-30', spec: 'API SN / ACEA A5/B5', capacityLiters: 4.0 },
    sparkPlugs: { type: 'Níquel / Iridio', spec: 'NGK LFR5A-11 / SILZKR6B10E', intervalKm: 30000 },
    brakeFluid: 'DOT 4',
    coolant: 'Verde / Azul OAT Long Life',
    transmissionFluid: 'SP-IV ATF / 75W-85 MTF',
    intervals: generateStandardIntervals('5W-30', 'NGK SILZKR6B10E'),
  },
  {
    id: 'kia-soluto-14',
    brand: 'Kia',
    model: 'Soluto 1.4 MPI',
    generationYears: '2019-2025',
    engineDisplacement: '1.4L Kappa MPI (94 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 0W-20', spec: 'API SN Plus / SP', capacityLiters: 3.5 },
    sparkPlugs: { type: 'Níquel', spec: 'NGK LZKR6B-10E', intervalKm: 25000 },
    brakeFluid: 'DOT 4',
    coolant: 'Verde/Azul OAT 50/50',
    intervals: generateStandardIntervals('5W-30', 'NGK LZKR6B'),
  },
  {
    id: 'kia-sonet-15',
    brand: 'Kia',
    model: 'Sonet 1.5 Smartstream',
    generationYears: '2021-2025',
    engineDisplacement: '1.5L Smartstream Gamma II (113 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'API SP / ILSAC GF-6', capacityLiters: 3.8 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK SILZKR6D8E', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Azul OAT Long Life',
    intervals: generateStandardIntervals('0W-20 Smartstream', 'NGK Iridio'),
  },
  {
    id: 'kia-picanto-12',
    brand: 'Kia',
    model: 'Picanto 1.0 / 1.2 (Morning / X-Line)',
    generationYears: '2012-2025',
    engineDisplacement: '1.0L / 1.2L Kappa MPI',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 10W-30', spec: 'API SN / SP', capacityLiters: 3.0 },
    sparkPlugs: { type: 'Cobre / Níquel', spec: 'NGK LKR6D-10E', intervalKm: 20000 },
    brakeFluid: 'DOT 4',
    coolant: 'Verde OAT 50/50',
    intervals: generateStandardIntervals('5W-30', 'NGK LKR6D-10E'),
  },
  {
    id: 'kia-rio-14',
    brand: 'Kia',
    model: 'Rio 1.4 / 1.6 (Sedan & Hatchback)',
    generationYears: '2012-2023',
    engineDisplacement: '1.4L / 1.6L Gamma MPI / D-CVVT',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 5W-20', spec: 'API SN / ILSAC GF-5', capacityLiters: 3.6 },
    sparkPlugs: { type: 'Níquel / Iridio', spec: 'NGK LZKR6B-10E', intervalKm: 30000 },
    brakeFluid: 'DOT 4',
    coolant: 'Verde OAT',
    intervals: generateStandardIntervals('5W-30', 'NGK LZKR6B'),
  },
  {
    id: 'kia-sorento-24',
    brand: 'Kia',
    model: 'Sorento 2.4 / 3.5 V6 / 2.2 CRDI',
    generationYears: '2015-2025',
    engineDisplacement: '2.4L Theta II / 3.5L Lambda V6 / 2.2L Diésel',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30', spec: 'API SN / ACEA A5', capacityLiters: 5.2 },
    sparkPlugs: { type: 'Iridio', spec: 'Denso / NGK Iridium', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Azul OAT',
    intervals: generateStandardIntervals('5W-30', 'Iridio OEM'),
  },
  {
    id: 'kia-seltos-16',
    brand: 'Kia',
    model: 'Seltos 1.6 / 1.4T / 1.5',
    generationYears: '2020-2025',
    engineDisplacement: '1.6L Gamma / 1.4L Turbo T-GDI',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 0W-20', spec: 'API SP / ILSAC GF-6', capacityLiters: 4.0 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK SILZKR6D8E', intervalKm: 40000 },
    brakeFluid: 'DOT 4',
    coolant: 'Azul OAT',
    intervals: generateStandardIntervals('5W-30', 'NGK Iridio'),
  },
  {
    id: 'kia-cerato-16',
    brand: 'Kia',
    model: 'Cerato 1.6 / 2.0 (Forte)',
    generationYears: '2014-2024',
    engineDisplacement: '1.6L Gamma / 2.0L Nu MPI',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30', spec: 'API SN / ILSAC GF-5', capacityLiters: 4.0 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK SILZKR6B10E', intervalKm: 40000 },
    brakeFluid: 'DOT 4',
    coolant: 'Verde/Azul OAT',
    intervals: generateStandardIntervals('5W-30', 'NGK Iridio'),
  },
  {
    id: 'kia-carens-15',
    brand: 'Kia',
    model: 'Carens 1.5 / 2.0 7-Pasajeros',
    generationYears: '2014-2025',
    engineDisplacement: '1.5L Smartstream / 2.0L Nu',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 0W-20', spec: 'API SP', capacityLiters: 4.0 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK Iridium', intervalKm: 40000 },
    brakeFluid: 'DOT 4',
    coolant: 'Azul OAT',
    intervals: generateStandardIntervals('5W-30', 'Iridio'),
  },
  {
    id: 'kia-k3-16',
    brand: 'Kia',
    model: 'K3 Sedan & Cross 1.6',
    generationYears: '2024-2026',
    engineDisplacement: '1.6L Smartstream MPI (121 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'API SP / ILSAC GF-6', capacityLiters: 3.8 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK SILZKR6D8E', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Azul OAT Long Life',
    intervals: generateStandardIntervals('0W-20', 'NGK Iridio'),
  },
  {
    id: 'kia-carnival-v6',
    brand: 'Kia',
    model: 'Carnival / Sedona 3.5 V6 / 2.2D',
    generationYears: '2016-2025',
    engineDisplacement: '3.5L Smartstream V6 / 2.2L Smartstream Diésel',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 0W-20', spec: 'API SP / ACEA C3', capacityLiters: 6.5 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK Iridium', intervalKm: 60000 },
    brakeFluid: 'DOT 4',
    coolant: 'Azul OAT',
    intervals: generateStandardIntervals('5W-30', 'Iridio V6'),
  },
  {
    id: 'kia-stonic-10t',
    brand: 'Kia',
    model: 'Stonic 1.0 T-GDI MHEV / 1.4',
    generationYears: '2020-2025',
    engineDisplacement: '1.0L Turbo Mild-Hybrid / 1.4L MPI',
    fuelType: 'hybrid',
    engineOil: { viscosity: '0W-20', spec: 'API SP / ILSAC GF-6', capacityLiters: 3.6 },
    sparkPlugs: { type: 'Iridio Turbo', spec: 'NGK SILZKR7B11', intervalKm: 40000 },
    brakeFluid: 'DOT 4',
    coolant: 'Azul OAT',
    intervals: generateStandardIntervals('0W-20', 'NGK Iridio Turbo'),
  },

  // ==========================================
  // HYUNDAI (12 Modelos)
  // ==========================================
  {
    id: 'hyundai-tucson-20',
    brand: 'Hyundai',
    model: 'Tucson 2.0 (ix35 / TL / NX4)',
    generationYears: '2012-2025',
    engineDisplacement: '2.0L Nu MPI / Smartstream G2.0 (154 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 0W-20', spec: 'API SP / ILSAC GF-6', capacityLiters: 4.0 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK SILZKR6B10E / Denso IXUH22I', intervalKm: 40000 },
    brakeFluid: 'DOT 4',
    coolant: 'Azul / Verde Hyundai Long Life',
    transmissionFluid: 'SP-IV ATF',
    intervals: generateStandardIntervals('5W-30', 'NGK SILZKR6B10E'),
  },
  {
    id: 'hyundai-grand-i10',
    brand: 'Hyundai',
    model: 'Grand i10 1.2 (Sedan & Hatch)',
    generationYears: '2015-2025',
    engineDisplacement: '1.2L Kappa Dual VTVT (83 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 10W-30', spec: 'API SN / SP', capacityLiters: 3.2 },
    sparkPlugs: { type: 'Níquel / Iridio', spec: 'NGK LKR6D-10E', intervalKm: 25000 },
    brakeFluid: 'DOT 4',
    coolant: 'Verde OAT 50/50',
    intervals: generateStandardIntervals('5W-30', 'NGK LKR6D-10E'),
  },
  {
    id: 'hyundai-creta-15',
    brand: 'Hyundai',
    model: 'Creta 1.5 / 1.6 / 1.4T',
    generationYears: '2017-2025',
    engineDisplacement: '1.5L Smartstream / 1.6L Gamma',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'API SP / ILSAC GF-6', capacityLiters: 3.8 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK SILZKR6D8E', intervalKm: 40000 },
    brakeFluid: 'DOT 4',
    coolant: 'Azul OAT',
    intervals: generateStandardIntervals('0W-20 / 5W-30', 'NGK Iridio'),
  },
  {
    id: 'hyundai-accent-14',
    brand: 'Hyundai',
    model: 'Accent 1.4 / 1.6 (Verna)',
    generationYears: '2012-2023',
    engineDisplacement: '1.4L / 1.6L Gamma D-CVVT',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 10W-30', spec: 'API SN / SP', capacityLiters: 3.5 },
    sparkPlugs: { type: 'Níquel', spec: 'NGK LZKR6B-10E', intervalKm: 25000 },
    brakeFluid: 'DOT 4',
    coolant: 'Verde OAT',
    intervals: generateStandardIntervals('5W-30', 'NGK LZKR6B'),
  },
  {
    id: 'hyundai-elantra-20',
    brand: 'Hyundai',
    model: 'Elantra 1.6 / 2.0',
    generationYears: '2014-2024',
    engineDisplacement: '2.0L Nu Atkinson / 1.6L Gamma',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 0W-20', spec: 'API SP', capacityLiters: 4.0 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK SILZKR6B10E', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Azul OAT',
    intervals: generateStandardIntervals('5W-30', 'NGK Iridio'),
  },
  {
    id: 'hyundai-santa-fe',
    brand: 'Hyundai',
    model: 'Santa Fe 2.4 / 3.5 V6 / 2.2D',
    generationYears: '2014-2025',
    engineDisplacement: '2.4L Theta II / 3.5L V6 / 2.2L CRDI',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30', spec: 'API SN / SP', capacityLiters: 5.5 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK Iridium', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Azul OAT',
    intervals: generateStandardIntervals('5W-30', 'Iridio'),
  },
  {
    id: 'hyundai-h1-diesel',
    brand: 'Hyundai',
    model: 'H-1 / Starex 2.5 CRDI',
    generationYears: '2010-2022',
    engineDisplacement: '2.5L A2 CRDI Turbo Diésel (170 HP)',
    fuelType: 'diesel',
    engineOil: { viscosity: '15W-40 / 5W-30', spec: 'API CJ-4 / CH-4', capacityLiters: 7.4 },
    brakeFluid: 'DOT 4',
    coolant: 'Verde OAT 50/50',
    intervals: generateStandardIntervals('15W-40 Diésel', 'CRDI Diésel'),
  },
  {
    id: 'hyundai-venue-16',
    brand: 'Hyundai',
    model: 'Venue 1.6 MPI',
    generationYears: '2020-2025',
    engineDisplacement: '1.6L Smartstream Gamma II (121 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'API SP / ILSAC GF-6', capacityLiters: 3.8 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK SILZKR6D8E', intervalKm: 40000 },
    brakeFluid: 'DOT 4',
    coolant: 'Azul OAT',
    intervals: generateStandardIntervals('0W-20', 'NGK Iridio'),
  },
  {
    id: 'hyundai-kona-hybrid',
    brand: 'Hyundai',
    model: 'Kona 1.6 Hybrid / 2.0',
    generationYears: '2020-2025',
    engineDisplacement: '1.6L Kappa GDI Hybrid (139 HP)',
    fuelType: 'hybrid',
    engineOil: { viscosity: '0W-20', spec: 'API SP / ILSAC GF-6', capacityLiters: 3.8 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK SILZKR7C11S', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Azul OAT (Doble circuito)',
    intervals: generateStandardIntervals('0W-20 Híbrido', 'NGK Iridio'),
  },
  {
    id: 'hyundai-staria-diesel',
    brand: 'Hyundai',
    model: 'Staria 2.2 CRDI / 3.5 V6',
    generationYears: '2022-2025',
    engineDisplacement: '2.2L R-II CRDI Turbo Diésel (177 HP)',
    fuelType: 'diesel',
    engineOil: { viscosity: '5W-30 / 0W-30', spec: 'ACEA C2 / C3 / API CK-4', capacityLiters: 7.2 },
    brakeFluid: 'DOT 4',
    coolant: 'Azul OAT',
    intervals: generateStandardIntervals('5W-30 Diésel C3', 'CRDI'),
  },
  {
    id: 'hyundai-atos-11',
    brand: 'Hyundai',
    model: 'Atos / Santro 1.0 / 1.1',
    generationYears: '2004-2015',
    engineDisplacement: '1.0L / 1.1L Epsilon G4HG',
    fuelType: 'gasoline',
    engineOil: { viscosity: '10W-30 / 10W-40', spec: 'API SN / SL', capacityLiters: 3.0 },
    sparkPlugs: { type: 'Cobre', spec: 'NGK BKR5E-11', intervalKm: 20000 },
    brakeFluid: 'DOT 4',
    coolant: 'Verde 50/50',
    intervals: generateStandardIntervals('10W-30', 'NGK BKR5E'),
  },
  {
    id: 'hyundai-getz-14',
    brand: 'Hyundai',
    model: 'Getz 1.4 / 1.6',
    generationYears: '2006-2012',
    engineDisplacement: '1.4L Alpha II DOHC 16V',
    fuelType: 'gasoline',
    engineOil: { viscosity: '10W-30 / 10W-40', spec: 'API SN', capacityLiters: 3.3 },
    sparkPlugs: { type: 'Cobre', spec: 'NGK BKR5E-11', intervalKm: 20000 },
    brakeFluid: 'DOT 4',
    coolant: 'Verde 50/50',
    intervals: generateStandardIntervals('10W-30', 'NGK BKR5E'),
  },

  // ==========================================
  // RENAULT (10 Modelos)
  // ==========================================
  {
    id: 'renault-duster-16',
    brand: 'Renault',
    model: 'Duster 1.6 / 2.0 / 1.3T',
    generationYears: '2013-2025',
    engineDisplacement: '1.6L K4M / H4M / 1.3L Turbo TCe (154 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 5W-40', spec: 'Renault RN0700 / RN0710 / RN17', capacityLiters: 4.5 },
    sparkPlugs: { type: 'Platino / Iridio', spec: 'NGK LZKAR7A / Champion', intervalKm: 30000 },
    brakeFluid: 'DOT 4',
    coolant: 'Amarillo / Verde Glacéol RX Type D',
    intervals: generateStandardIntervals('5W-40 / 5W-30 RN0710', 'Renault Iridio'),
  },
  {
    id: 'renault-stepway-16',
    brand: 'Renault',
    model: 'Stepway 1.6 16V',
    generationYears: '2012-2024',
    engineDisplacement: '1.6L K4M / H4M HR16DE (111 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 10W-40', spec: 'Renault RN0700 / API SN', capacityLiters: 4.2 },
    sparkPlugs: { type: 'Cobre', spec: 'NGK BKR6E / LZKAR7A', intervalKm: 25000 },
    brakeFluid: 'DOT 4',
    coolant: 'Glacéol RX Type D (Amarillo)',
    intervals: generateStandardIntervals('5W-30 RN0700', 'NGK BKR6E'),
  },
  {
    id: 'renault-logan-16',
    brand: 'Renault',
    model: 'Logan 1.6 (8V & 16V)',
    generationYears: '2010-2024',
    engineDisplacement: '1.6L K7M 8V / K4M 16V / H4M',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 10W-40', spec: 'Renault RN0700 / API SN', capacityLiters: 3.8 },
    sparkPlugs: { type: 'Cobre', spec: 'NGK BKR6E / Eyquem', intervalKm: 20000 },
    brakeFluid: 'DOT 4',
    coolant: 'Glacéol RX Type D',
    intervals: generateStandardIntervals('10W-40 / 5W-30', 'NGK BKR6E'),
  },
  {
    id: 'renault-sandero-16',
    brand: 'Renault',
    model: 'Sandero 1.6 / RS 2.0',
    generationYears: '2011-2023',
    engineDisplacement: '1.6L K4M / 2.0L F4R (145 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-40 / 5W-30', spec: 'Renault RN0710 / RN0700', capacityLiters: 4.5 },
    sparkPlugs: { type: 'Iridio / Platino', spec: 'NGK PFR6G-9', intervalKm: 30000 },
    brakeFluid: 'DOT 4',
    coolant: 'Glacéol RX Type D',
    intervals: generateStandardIntervals('5W-40 RN0710', 'NGK Platino'),
  },
  {
    id: 'renault-kwid-10',
    brand: 'Renault',
    model: 'Kwid 1.0 SCe',
    generationYears: '2019-2025',
    engineDisplacement: '1.0L 3-Cilindros SCe (66 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 10W-40', spec: 'Renault RN0700 / API SN', capacityLiters: 3.0 },
    sparkPlugs: { type: 'Cobre / Níquel', spec: 'NGK LKAR7A-9', intervalKm: 20000 },
    brakeFluid: 'DOT 4',
    coolant: 'Glacéol RX Type D',
    intervals: generateStandardIntervals('5W-30 RN0700', 'NGK LKAR7A-9'),
  },
  {
    id: 'renault-koleos-25',
    brand: 'Renault',
    model: 'Koleos 2.5 CVT 4x4',
    generationYears: '2012-2024',
    engineDisplacement: '2.5L QR25DE (170 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30', spec: 'RN0700 / API SN / ILSAC GF-5', capacityLiters: 4.8 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK DILKAR6A11', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Glacéol RX Type D',
    intervals: generateStandardIntervals('5W-30', 'NGK Iridio'),
  },
  {
    id: 'renault-captur-20',
    brand: 'Renault',
    model: 'Captur 2.0 / 1.3T',
    generationYears: '2017-2024',
    engineDisplacement: '2.0L F4R / 1.3L TCe Turbo',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-40 / 5W-30', spec: 'RN0710 / RN17', capacityLiters: 5.0 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK ILKAR7J7G', intervalKm: 40000 },
    brakeFluid: 'DOT 4',
    coolant: 'Glacéol RX Type D',
    intervals: generateStandardIntervals('5W-40 RN0710', 'NGK Iridio'),
  },
  {
    id: 'renault-kangoo-16',
    brand: 'Renault',
    model: 'Kangoo 1.6 / 1.5 dCi',
    generationYears: '2012-2024',
    engineDisplacement: '1.6L SCe / 1.5L dCi Diésel',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 5W-40', spec: 'RN0700 / RN0720 Diésel', capacityLiters: 4.5 },
    sparkPlugs: { type: 'Cobre', spec: 'NGK BKR6E', intervalKm: 25000 },
    brakeFluid: 'DOT 4',
    coolant: 'Glacéol RX Type D',
    intervals: generateStandardIntervals('5W-30', 'OEM'),
  },
  {
    id: 'renault-master-diesel',
    brand: 'Renault',
    model: 'Master 2.3 dCi Turbo Diésel',
    generationYears: '2015-2025',
    engineDisplacement: '2.3L dCi M9T Turbo Diésel (130 HP)',
    fuelType: 'diesel',
    engineOil: { viscosity: '5W-30 / 5W-40', spec: 'Renault RN0720 Low SAPS', capacityLiters: 8.0 },
    brakeFluid: 'DOT 4',
    coolant: 'Glacéol RX Type D',
    intervals: generateStandardIntervals('5W-30 RN0720 Diésel', 'dCi'),
  },
  {
    id: 'renault-oroch-20',
    brand: 'Renault',
    model: 'Oroch 2.0 / 1.3T 4x4',
    generationYears: '2016-2025',
    engineDisplacement: '2.0L F4R / 1.3L Turbo TCe',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-40 / 5W-30', spec: 'RN0710 / RN17', capacityLiters: 4.8 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK Iridium', intervalKm: 40000 },
    brakeFluid: 'DOT 4',
    coolant: 'Glacéol RX Type D',
    intervals: generateStandardIntervals('5W-40', 'Iridio'),
  },

  // ==========================================
  // NISSAN (10 Modelos)
  // ==========================================
  {
    id: 'nissan-frontier-np300',
    brand: 'Nissan',
    model: 'Frontier / NP300 2.5 Diésel & Gasolina',
    generationYears: '2016-2025',
    engineDisplacement: '2.5L YD25DDTi Turbo Diésel / 2.5L QR25DE Gasolina',
    fuelType: 'diesel',
    engineOil: { viscosity: '5W-30 / 15W-40', spec: 'API CJ-4 / CK-4 / ACEA C3', capacityLiters: 6.8 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK DILKAR6A11 (Gasolina)', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Nissan Long Life Coolant (Verde / Azul)',
    intervals: generateStandardIntervals('5W-30 / 15W-40 Diésel', 'YD25'),
  },
  {
    id: 'nissan-versa-16',
    brand: 'Nissan',
    model: 'Versa 1.6 (Drive / Advance / Exclusive)',
    generationYears: '2012-2025',
    engineDisplacement: '1.6L HR16DE DOHC 16V (118 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 0W-20', spec: 'API SP / ILSAC GF-6', capacityLiters: 3.5 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK DILKAR6A11 / Denso FXE20HR11', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Nissan L248SP Azul 50/50',
    transmissionFluid: 'Nissan NS-3 CVT / 75W Manual',
    intervals: generateStandardIntervals('5W-30 / 0W-20', 'NGK DILKAR6A11 Iridio'),
  },
  {
    id: 'nissan-kicks-16',
    brand: 'Nissan',
    model: 'Kicks 1.6',
    generationYears: '2017-2025',
    engineDisplacement: '1.6L HR16DE (118 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'API SP / ILSAC GF-6', capacityLiters: 3.5 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK DILKAR6A11', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Nissan Azul 50/50',
    intervals: generateStandardIntervals('0W-20 / 5W-30', 'NGK DILKAR6A11'),
  },
  {
    id: 'nissan-sentra-20',
    brand: 'Nissan',
    model: 'Sentra 1.8 / 2.0 (B17 / B18)',
    generationYears: '2013-2025',
    engineDisplacement: '1.8L MRA8DE / 2.0L MR20DD (149 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'API SP', capacityLiters: 4.0 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK DILKAR7D11H', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Nissan Azul L248',
    intervals: generateStandardIntervals('0W-20 Sentra', 'NGK Iridio'),
  },
  {
    id: 'nissan-qashqai-20',
    brand: 'Nissan',
    model: 'Qashqai 2.0 / 1.3T',
    generationYears: '2014-2025',
    engineDisplacement: '2.0L MR20DD / 1.3L Turbo DIG-T',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 0W-20', spec: 'API SP / ACEA C3', capacityLiters: 4.2 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK DILKAR7D11H', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Nissan Azul',
    intervals: generateStandardIntervals('5W-30', 'NGK Iridio'),
  },
  {
    id: 'nissan-xtrail-25',
    brand: 'Nissan',
    model: 'X-Trail 2.5 / e-POWER',
    generationYears: '2015-2025',
    engineDisplacement: '2.5L QR25DE (170 HP) / 1.5T e-POWER',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'API SP / ILSAC GF-6', capacityLiters: 4.8 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK DILKAR6A11', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Nissan Azul L248',
    intervals: generateStandardIntervals('0W-20 / 5W-30', 'NGK DILKAR6A11'),
  },
  {
    id: 'nissan-march-16',
    brand: 'Nissan',
    model: 'March 1.6 (Micra)',
    generationYears: '2012-2024',
    engineDisplacement: '1.6L HR16DE (106 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 10W-30', spec: 'API SN / SP', capacityLiters: 3.2 },
    sparkPlugs: { type: 'Platino / Iridio', spec: 'NGK PLKAR6A-11', intervalKm: 35000 },
    brakeFluid: 'DOT 4',
    coolant: 'Nissan Verde/Azul',
    intervals: generateStandardIntervals('5W-30', 'NGK Platino'),
  },
  {
    id: 'nissan-tiida-18',
    brand: 'Nissan',
    model: 'Tiida 1.6 / 1.8 (Sedan & Hatch)',
    generationYears: '2007-2018',
    engineDisplacement: '1.6L HR16DE / 1.8L MR18DE (125 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '10W-30 / 5W-30', spec: 'API SN', capacityLiters: 3.8 },
    sparkPlugs: { type: 'Platino', spec: 'NGK PLZKAR6A-11', intervalKm: 35000 },
    brakeFluid: 'DOT 4',
    coolant: 'Nissan Verde',
    intervals: generateStandardIntervals('10W-30 / 5W-30', 'NGK PLZKAR6A-11'),
  },
  {
    id: 'nissan-patrol-v8',
    brand: 'Nissan',
    model: 'Patrol 4.8 / 5.6 V8 (Y61 / Y62)',
    generationYears: '2010-2025',
    engineDisplacement: '5.6L VK56VD V8 (400 HP) / 4.8L TB48DE',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 5W-40', spec: 'API SN / SP', capacityLiters: 6.8 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK DILKAR7B11', intervalKm: 60000 },
    brakeFluid: 'DOT 4',
    coolant: 'Nissan Azul',
    intervals: generateStandardIntervals('5W-40 V8', 'NGK Iridio V8'),
  },
  {
    id: 'nissan-pathfinder-v6',
    brand: 'Nissan',
    model: 'Pathfinder 3.5 V6',
    generationYears: '2013-2024',
    engineDisplacement: '3.5L VQ35DE / VQ35DD V6 (284 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'API SP', capacityLiters: 5.1 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK DILKAR7D11H', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Nissan Azul',
    intervals: generateStandardIntervals('0W-20 V6', 'NGK Iridio'),
  },

  // ==========================================
  // SUZUKI (8 Modelos)
  // ==========================================
  {
    id: 'suzuki-vitara-live',
    brand: 'Suzuki',
    model: 'Vitara Live / Boosterjet 1.6 / 1.4T',
    generationYears: '2016-2025',
    engineDisplacement: '1.6L M16A (118 HP) / 1.4L Boosterjet Turbo (138 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'API SP / ILSAC GF-6', capacityLiters: 3.9 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK SILFR6A11 / IFR6J11', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Suzuki Super Coolant Azul',
    intervals: generateStandardIntervals('0W-20 / 5W-30', 'NGK Iridio'),
  },
  {
    id: 'suzuki-jimny-15',
    brand: 'Suzuki',
    model: 'Jimny 1.3 / 1.5 4x4 (JB74)',
    generationYears: '2012-2025',
    engineDisplacement: '1.5L K15B (102 HP) / 1.3L M13A',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'API SP / ILSAC GF-6', capacityLiters: 3.6 },
    sparkPlugs: { type: 'Iridio / Níquel', spec: 'Denso KR6A-10 / NGK IFR6J11', intervalKm: 35000 },
    brakeFluid: 'DOT 4',
    coolant: 'Suzuki Super Coolant Azul',
    transmissionFluid: '75W-90 GL-4 / Suzuki 4x4 Transfer',
    intervals: generateStandardIntervals('0W-20 / 5W-30', 'Jimny Iridio'),
  },
  {
    id: 'suzuki-swift-12',
    brand: 'Suzuki',
    model: 'Swift 1.2 / Boosterjet 1.0T / 1.4T Sport',
    generationYears: '2012-2025',
    engineDisplacement: '1.2L K12M / K12N Dualjet / 1.4L Boosterjet Sport',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'API SP / ILSAC GF-6', capacityLiters: 3.3 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK ILZKR7D8', intervalKm: 40000 },
    brakeFluid: 'DOT 4',
    coolant: 'Suzuki Azul',
    intervals: generateStandardIntervals('0W-20', 'NGK Iridio'),
  },
  {
    id: 'suzuki-scross-16',
    brand: 'Suzuki',
    model: 'S-Cross 1.6 / 1.4T AllGrip',
    generationYears: '2015-2025',
    engineDisplacement: '1.6L M16A / 1.4L Boosterjet',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'API SP', capacityLiters: 3.9 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK IFR6J11', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Suzuki Azul',
    intervals: generateStandardIntervals('0W-20', 'NGK Iridio'),
  },
  {
    id: 'suzuki-baleno-14',
    brand: 'Suzuki',
    model: 'Baleno 1.4 / 1.5 K15B',
    generationYears: '2017-2025',
    engineDisplacement: '1.4L K14B / 1.5L K15B',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'API SP', capacityLiters: 3.2 },
    sparkPlugs: { type: 'Níquel / Iridio', spec: 'NGK KR6A-10', intervalKm: 30000 },
    brakeFluid: 'DOT 4',
    coolant: 'Suzuki Azul',
    intervals: generateStandardIntervals('0W-20', 'NGK KR6A-10'),
  },
  {
    id: 'suzuki-alto-800',
    brand: 'Suzuki',
    model: 'Alto 800 / K10',
    generationYears: '2010-2024',
    engineDisplacement: '0.8L F8D / 1.0L K10B',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 10W-30', spec: 'API SN', capacityLiters: 2.8 },
    sparkPlugs: { type: 'Cobre', spec: 'NGK BKR6E', intervalKm: 20000 },
    brakeFluid: 'DOT 4',
    coolant: 'Verde 50/50',
    intervals: generateStandardIntervals('5W-30', 'NGK BKR6E'),
  },
  {
    id: 'suzuki-grand-vitara-hybrid',
    brand: 'Suzuki',
    model: 'Grand Vitara Hybrid (2023+)',
    generationYears: '2023-2026',
    engineDisplacement: '1.5L K15C Dualjet Boostergreen MHEV',
    fuelType: 'hybrid',
    engineOil: { viscosity: '0W-16 / 0W-20', spec: 'API SP / ILSAC GF-6B', capacityLiters: 3.5 },
    sparkPlugs: { type: 'Iridio', spec: 'Denso / NGK Iridium', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Suzuki Super Coolant Azul',
    intervals: generateStandardIntervals('0W-16 Boostergreen', 'Iridio'),
  },
  {
    id: 'suzuki-celerio-10',
    brand: 'Suzuki',
    model: 'Celerio 1.0 K10C Dualjet',
    generationYears: '2015-2025',
    engineDisplacement: '1.0L 3-Cilindros K10C',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'API SP', capacityLiters: 3.0 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK ILZKR7D8', intervalKm: 40000 },
    brakeFluid: 'DOT 4',
    coolant: 'Suzuki Azul',
    intervals: generateStandardIntervals('0W-20', 'NGK Iridio'),
  },

  // ==========================================
  // CHERY / GREAT WALL / HAVAL / JAC / JETOUR / GEELY (12 Modelos)
  // ==========================================
  {
    id: 'chery-tiggo-2',
    brand: 'Chery',
    model: 'Tiggo 2 / Tiggo 2 Pro 1.5',
    generationYears: '2018-2025',
    engineDisplacement: '1.5L Acteco DOHC 16V (105 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30', spec: 'API SN / SP', capacityLiters: 3.8 },
    sparkPlugs: { type: 'Iridio / Níquel', spec: 'Torch K6RTC / NGK BKR6E', intervalKm: 25000 },
    brakeFluid: 'DOT 4',
    coolant: 'Rojo OAT 50/50',
    intervals: generateStandardIntervals('5W-30', 'Torch / NGK BKR6E'),
  },
  {
    id: 'chery-tiggo-4',
    brand: 'Chery',
    model: 'Tiggo 4 / Tiggo 4 Pro 1.5T',
    generationYears: '2020-2025',
    engineDisplacement: '1.5L Turbo Acteco (145 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 5W-40', spec: 'API SP / ACEA C3', capacityLiters: 4.2 },
    sparkPlugs: { type: 'Iridio', spec: 'Torch Iridium / Denso IXUH22I', intervalKm: 40000 },
    brakeFluid: 'DOT 4',
    coolant: 'Rojo OAT',
    intervals: generateStandardIntervals('5W-30 Turbo', 'Iridio Torch'),
  },
  {
    id: 'chery-tiggo-7-pro',
    brand: 'Chery',
    model: 'Tiggo 7 Pro 1.5T',
    generationYears: '2021-2025',
    engineDisplacement: '1.5L Turbo Acteco (145 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30', spec: 'API SP / Dexos 1', capacityLiters: 4.5 },
    sparkPlugs: { type: 'Iridio', spec: 'Denso Iridium', intervalKm: 40000 },
    brakeFluid: 'DOT 4',
    coolant: 'Rojo OAT',
    intervals: generateStandardIntervals('5W-30', 'Denso Iridio'),
  },
  {
    id: 'chery-tiggo-8-pro',
    brand: 'Chery',
    model: 'Tiggo 8 Pro 1.6T / 2.0T',
    generationYears: '2021-2025',
    engineDisplacement: '1.6L TGDI (183 HP) / 2.0L TGDI (250 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'API SP / ACEA C5/C3', capacityLiters: 4.8 },
    sparkPlugs: { type: 'Iridio', spec: 'Bosch / NGK Iridium', intervalKm: 40000 },
    brakeFluid: 'DOT 4',
    coolant: 'Rojo OAT',
    intervals: generateStandardIntervals('0W-20 / 5W-30 TGDI', 'Iridio TGDI'),
  },
  {
    id: 'haval-h6-turbo',
    brand: 'Great Wall',
    model: 'Haval H6 1.5T / 2.0T / Hybrid',
    generationYears: '2019-2025',
    engineDisplacement: '1.5L GDIT (169 HP) / 2.0L GDIT / Híbrido DHT',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'API SP / ACEA C2', capacityLiters: 4.5 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK SILZKFR8D7S', intervalKm: 40000 },
    brakeFluid: 'DOT 4',
    coolant: 'OAT Rojo 50/50',
    intervals: generateStandardIntervals('0W-20 / 5W-30', 'NGK Iridio GDIT'),
  },
  {
    id: 'great-wall-poer-diesel',
    brand: 'Great Wall',
    model: 'Great Wall Poer 2.0 Turbo Diésel 4x4',
    generationYears: '2021-2025',
    engineDisplacement: '2.0L GW4D20M Turbo Diésel (161 HP / 400 Nm)',
    fuelType: 'diesel',
    engineOil: { viscosity: '5W-30 / 5W-40', spec: 'ACEA C3 / API CK-4 / DPF', capacityLiters: 6.0 },
    brakeFluid: 'DOT 4',
    coolant: 'OAT Rojo 50/50',
    intervals: generateStandardIntervals('5W-30 Diésel C3', 'GW4D20M Diésel'),
  },
  {
    id: 'great-wall-wingle-7',
    brand: 'Great Wall',
    model: 'Wingle 5 / Wingle 7 2.0 Diésel & Gasolina',
    generationYears: '2015-2025',
    engineDisplacement: '2.0L GW4D20 Turbo Diésel / 2.4L 4G69 Gasolina',
    fuelType: 'diesel',
    engineOil: { viscosity: '15W-40 / 5W-30', spec: 'API CJ-4 / CK-4', capacityLiters: 6.0 },
    brakeFluid: 'DOT 4',
    coolant: 'Rojo OAT',
    intervals: generateStandardIntervals('15W-40 Diésel', 'Wingle'),
  },
  {
    id: 'jac-t6-t8-diesel',
    brand: 'JAC',
    model: 'JAC T6 / T8 / T8 Pro 2.0 CTI Diésel',
    generationYears: '2018-2025',
    engineDisplacement: '2.0L CTI Turbo Diésel Intercooler (137 HP)',
    fuelType: 'diesel',
    engineOil: { viscosity: '5W-30 / 15W-40', spec: 'API CJ-4 / CK-4 / ACEA C3', capacityLiters: 6.0 },
    brakeFluid: 'DOT 4',
    coolant: 'OAT Rojo 50/50',
    intervals: generateStandardIntervals('5W-30 / 15W-40 CTI', 'CTI Diésel'),
  },
  {
    id: 'jac-js2-js4',
    brand: 'JAC',
    model: 'JAC JS2 / JS4 1.5',
    generationYears: '2019-2025',
    engineDisplacement: '1.5L DOHC 16V (111 HP) / 1.5L Turbo',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30', spec: 'API SN / SP', capacityLiters: 3.8 },
    sparkPlugs: { type: 'Iridio / Níquel', spec: 'Torch / NGK', intervalKm: 30000 },
    brakeFluid: 'DOT 4',
    coolant: 'Rojo OAT',
    intervals: generateStandardIntervals('5W-30', 'Iridio Torch'),
  },
  {
    id: 'jetour-x70-15t',
    brand: 'Jetour',
    model: 'Jetour X70 / X70 Plus 1.5T / 1.6T',
    generationYears: '2020-2025',
    engineDisplacement: '1.5L Turbo Acteco (147 HP) / 1.6L TGDI',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 0W-20', spec: 'API SP / ACEA C3', capacityLiters: 4.5 },
    sparkPlugs: { type: 'Iridio', spec: 'Denso / Torch Iridium', intervalKm: 40000 },
    brakeFluid: 'DOT 4',
    coolant: 'Rojo OAT',
    intervals: generateStandardIntervals('5W-30 Turbo', 'Iridio'),
  },
  {
    id: 'geely-coolray-15t',
    brand: 'Geely',
    model: 'Coolray 1.5 Turbo 3/4-Cilindros',
    generationYears: '2021-2025',
    engineDisplacement: '1.5L Turbo TD (177 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20', spec: 'Volvo VCC RBS0-2AE / API SP', capacityLiters: 5.6 },
    sparkPlugs: { type: 'Iridio', spec: 'Volvo / Geely Iridium', intervalKm: 40000 },
    brakeFluid: 'DOT 4',
    coolant: 'Azul / Verde OAT',
    intervals: generateStandardIntervals('0W-20 Volvo Spec', 'Iridio Turbo'),
  },
  {
    id: 'geely-emgrand-15',
    brand: 'Geely',
    model: 'Emgrand 1.5 (Sedan)',
    generationYears: '2022-2025',
    engineDisplacement: '1.5L DOHC DVVT (101 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 0W-20', spec: 'API SP', capacityLiters: 3.8 },
    sparkPlugs: { type: 'Iridio', spec: 'Torch / NGK', intervalKm: 40000 },
    brakeFluid: 'DOT 4',
    coolant: 'Rojo OAT',
    intervals: generateStandardIntervals('5W-30', 'Iridio'),
  },

  // ==========================================
  // VOLKSWAGEN / FORD / MAZDA / HONDA / MITSUBISHI / OTROS (16 Modelos)
  // ==========================================
  {
    id: 'vw-amarok-v6',
    brand: 'Volkswagen',
    model: 'Amarok 2.0 BiTDI / 3.0 V6 TDI',
    generationYears: '2012-2025',
    engineDisplacement: '2.0L BiTDI (180 HP) / 3.0L V6 TDI (258 HP)',
    fuelType: 'diesel',
    engineOil: { viscosity: '5W-30', spec: 'VW 507.00 / 504.00 Long Life', capacityLiters: 7.0 },
    brakeFluid: 'DOT 4 Low Viscosity',
    coolant: 'VW G12evo / G13 Rosa',
    intervals: generateStandardIntervals('5W-30 VW 507.00', 'TDI'),
  },
  {
    id: 'vw-gol-16',
    brand: 'Volkswagen',
    model: 'Gol / Voyage / Saveiro 1.6 MSI',
    generationYears: '2010-2024',
    engineDisplacement: '1.6L EA111 8V (101 HP) / 1.6L EA211 16V (110 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-40 / 5W-30', spec: 'VW 502.00 / 505.00', capacityLiters: 4.0 },
    sparkPlugs: { type: 'Cobre / Platino', spec: 'NGK BKR7ES / PZFR6R', intervalKm: 30000 },
    brakeFluid: 'DOT 4',
    coolant: 'VW G12 / G13 Rosa',
    intervals: generateStandardIntervals('5W-40 VW 502.00', 'NGK BKR7ES'),
  },
  {
    id: 'vw-tcross-turbo',
    brand: 'Volkswagen',
    model: 'T-Cross / Nivus 1.0 TSI (200 TSI)',
    generationYears: '2020-2025',
    engineDisplacement: '1.0L 3-Cilindros TSI Turbo (116 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'VW 508.00 / 502.00 504.00', capacityLiters: 4.0 },
    sparkPlugs: { type: 'Iridio Platino', spec: 'NGK ILKER7A8EGS', intervalKm: 40000 },
    brakeFluid: 'DOT 4 LV',
    coolant: 'VW G12evo Rosa',
    intervals: generateStandardIntervals('0W-20 / 5W-40 TSI', 'NGK Iridio TSI'),
  },
  {
    id: 'ford-f150-v6-v8',
    brand: 'Ford',
    model: 'F-150 3.5 EcoBoost / 5.0 V8',
    generationYears: '2015-2025',
    engineDisplacement: '3.5L V6 Twin-Turbo EcoBoost / 5.0L Coyote V8',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 5W-20', spec: 'Motorcraft WSS-M2C961-A1 / API SP', capacityLiters: 5.7 },
    sparkPlugs: { type: 'Iridio Platino', spec: 'Motorcraft SP-580 Iridium', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Motorcraft Yellow OAT',
    intervals: generateStandardIntervals('5W-30 Motorcraft', 'Motorcraft Iridio'),
  },
  {
    id: 'ford-ranger-diesel',
    brand: 'Ford',
    model: 'Ranger 2.0 Biturbo / 3.2 TDCi / 3.0 V6',
    generationYears: '2014-2025',
    engineDisplacement: '3.2L Puma TDCi (200 HP) / 2.0L EcoBlue / 3.0L V6',
    fuelType: 'diesel',
    engineOil: { viscosity: '5W-30 / 0W-30', spec: 'WSS-M2C913-D / WSS-M2C950-A', capacityLiters: 9.8 },
    brakeFluid: 'DOT 4',
    coolant: 'Motorcraft Orange / Yellow',
    intervals: generateStandardIntervals('5W-30 TDCi', 'TDCi'),
  },
  {
    id: 'ford-explorer-v6',
    brand: 'Ford',
    model: 'Explorer 2.3 EcoBoost / 3.5 V6',
    generationYears: '2014-2024',
    engineDisplacement: '2.3L Turbo / 3.5L Cyclone V6 (290 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '5W-30 / 5W-20', spec: 'Motorcraft API SP', capacityLiters: 5.7 },
    sparkPlugs: { type: 'Iridio', spec: 'Motorcraft SP-520', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Motorcraft Yellow',
    intervals: generateStandardIntervals('5W-30', 'Motorcraft Iridio'),
  },
  {
    id: 'mazda-3-skyactiv',
    brand: 'Mazda',
    model: 'Mazda 3 2.0 / 2.5 Skyactiv-G',
    generationYears: '2014-2025',
    engineDisplacement: '2.0L / 2.5L Skyactiv-G (153 HP / 186 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'Mazda Original Oil / API SP / ILSAC GF-6', capacityLiters: 4.2 },
    sparkPlugs: { type: 'Iridio', spec: 'Denso PE5R-18-110 / NGK ILKAR7L11', intervalKm: 60000 },
    brakeFluid: 'DOT 4',
    coolant: 'Mazda FL22 Verde Long Life',
    intervals: generateStandardIntervals('0W-20 Skyactiv', 'Denso Iridio'),
  },
  {
    id: 'mazda-cx5-skyactiv',
    brand: 'Mazda',
    model: 'Mazda CX-5 2.0 / 2.5 Skyactiv-G',
    generationYears: '2015-2025',
    engineDisplacement: '2.0L / 2.5L Skyactiv-G / 2.5L Turbo',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'API SP / ILSAC GF-6', capacityLiters: 4.5 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK ILKAR7L11', intervalKm: 60000 },
    brakeFluid: 'DOT 4',
    coolant: 'Mazda FL22 Verde',
    intervals: generateStandardIntervals('0W-20 / 5W-30', 'NGK Iridio'),
  },
  {
    id: 'mazda-bt50-diesel',
    brand: 'Mazda',
    model: 'Mazda BT-50 2.2 / 3.2 / 3.0 D-Max platform',
    generationYears: '2013-2025',
    engineDisplacement: '3.2L MZ-CD / 3.0L Isuzu 4JJ3 Turbo Diésel',
    fuelType: 'diesel',
    engineOil: { viscosity: '5W-30 / 15W-40', spec: 'API CK-4 / CJ-4', capacityLiters: 7.5 },
    brakeFluid: 'DOT 4',
    coolant: 'Mazda FL22',
    intervals: generateStandardIntervals('5W-30 Diésel', 'Common Rail'),
  },
  {
    id: 'honda-crv-turbo',
    brand: 'Honda',
    model: 'Honda CR-V 1.5 Turbo / 2.4 / Hybrid',
    generationYears: '2015-2025',
    engineDisplacement: '1.5L VTEC Turbo (190 HP) / 2.4L Earth Dreams',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20', spec: 'Honda Ultimate Full Synthetic / API SP', capacityLiters: 3.5 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK DILKAR8J9G / Denso DXE22H11', intervalKm: 50000 },
    brakeFluid: 'DOT 4 / DOT 3',
    coolant: 'Honda Type 2 Azul 50/50',
    transmissionFluid: 'Honda HCF-2 CVT Fluid',
    intervals: generateStandardIntervals('0W-20 Honda', 'NGK DILKAR8J9G'),
  },
  {
    id: 'honda-civic-turbo',
    brand: 'Honda',
    model: 'Honda Civic 1.5T / 2.0',
    generationYears: '2016-2025',
    engineDisplacement: '1.5L VTEC Turbo (180 HP) / 2.0L K20C',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20', spec: 'API SP / ILSAC GF-6', capacityLiters: 3.5 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK DILKAR8J9G', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Honda Type 2 Azul',
    intervals: generateStandardIntervals('0W-20', 'NGK Iridio'),
  },
  {
    id: 'mitsubishi-l200-diesel',
    brand: 'Mitsubishi',
    model: 'L200 / Triton 2.4 / 2.5 DI-D Turbo Diésel',
    generationYears: '2015-2025',
    engineDisplacement: '2.4L 4N15 MIVEC Clean Diésel (178 HP)',
    fuelType: 'diesel',
    engineOil: { viscosity: '5W-30 / 15W-40', spec: 'ACEA C3 / API CK-4 / DPF', capacityLiters: 7.5 },
    brakeFluid: 'DOT 4',
    coolant: 'Mitsubishi Super Long Life Coolant Azul',
    intervals: generateStandardIntervals('5W-30 Diésel C3', 'DI-D MIVEC'),
  },
  {
    id: 'mitsubishi-outlander-24',
    brand: 'Mitsubishi',
    model: 'Outlander 2.4 / 2.5 / PHEV',
    generationYears: '2014-2025',
    engineDisplacement: '2.4L 4B12 MIVEC / 2.5L PR25DD',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'API SP / ILSAC GF-6', capacityLiters: 4.6 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK DILKR7B6 / Denso', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Mitsubishi SLLC Azul',
    intervals: generateStandardIntervals('0W-20', 'NGK Iridio'),
  },
  {
    id: 'jeep-wrangler-v6',
    brand: 'Jeep',
    model: 'Wrangler / Grand Cherokee 3.6 V6 Pentastar',
    generationYears: '2012-2025',
    engineDisplacement: '3.6L Pentastar V6 (285 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-20', spec: 'Chrysler MS-6395 / API SP', capacityLiters: 4.7 },
    sparkPlugs: { type: 'Iridio', spec: 'Champion RER8ZWYCB4', intervalKm: 50000 },
    brakeFluid: 'DOT 4',
    coolant: 'Mopar OAT Púrpura 50/50',
    intervals: generateStandardIntervals('0W-20 Mopar', 'Pentastar V6'),
  },
  {
    id: 'peugeot-2008-puretech',
    brand: 'Peugeot',
    model: '2008 / 3008 1.2 PureTech / 1.6 THP',
    generationYears: '2018-2025',
    engineDisplacement: '1.2L 3-Cilindros PureTech Turbo (130 HP) / 1.6L THP',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 0W-30', spec: 'PSA B71 2010 / B71 2312 (Correa húmeda)', capacityLiters: 3.5 },
    sparkPlugs: { type: 'Iridio', spec: 'NGK ILZKBR7B8DG', intervalKm: 35000 },
    brakeFluid: 'DOT 4 LV',
    coolant: 'PSA Long Life Azul-Verde',
    intervals: generateStandardIntervals('0W-20 PSA B71 2010', 'NGK Iridio'),
  },
  {
    id: 'fiat-strada-firefly',
    brand: 'Fiat',
    model: 'Strada / Pulse / Cronos 1.3 Firefly',
    generationYears: '2018-2025',
    engineDisplacement: '1.3L Firefly 8V (99 HP)',
    fuelType: 'gasoline',
    engineOil: { viscosity: '0W-20 / 5W-30', spec: 'Fiat 9.55535-GS1 / API SP', capacityLiters: 3.5 },
    sparkPlugs: { type: 'Níquel / Iridio', spec: 'NGK KR6G-10D', intervalKm: 30000 },
    brakeFluid: 'DOT 4',
    coolant: 'Petronas Paraflu UP Rojo',
    intervals: generateStandardIntervals('0W-20 / 5W-30', 'NGK Firefly'),
  },
];

/**
 * Return list of all unique brands in the master catalog.
 */
export function getAvailableBrands(): string[] {
  const brands = Array.from(new Set(MASTER_VEHICLE_CATALOG.map((v) => v.brand)));
  return brands.sort();
}

/**
 * Return list of all models for a specific brand.
 */
export function getModelsByBrand(brand: string): string[] {
  return MASTER_VEHICLE_CATALOG.filter(
    (v) => v.brand.toLowerCase() === brand.toLowerCase()
  ).map((v) => v.model);
}

/**
 * Find maintenance template by brand and model name.
 */
export function findMaintenanceTemplate(
  brand: string,
  model: string
): MaintenanceTemplate | undefined {
  const b = brand.toLowerCase().trim();
  const m = model.toLowerCase().trim();

  return MASTER_VEHICLE_CATALOG.find(
    (v) =>
      v.brand.toLowerCase() === b &&
      (v.model.toLowerCase() === m ||
        v.model.toLowerCase().includes(m) ||
        m.includes(v.model.toLowerCase().split(' ')[0]))
  );
}
