import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';

const rootDir = process.cwd();
const pkgPath = path.join(rootDir, 'package.json');
const versionTsPath = path.join(rootDir, 'lib', 'version.ts');

const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
const currentVersion = pkg.version || '0.1.0';
const parts = currentVersion.split('.').map(Number);

// Bump patch version
parts[2] = (parts[2] || 0) + 1;
const newVersion = parts.join('.');
pkg.version = newVersion;

fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');

let gitCommit = 'local';
try {
  gitCommit = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
} catch {}

const timestamp = new Date().toISOString();

const content = `// Auto-generated by scripts/bump-version.mjs — do not edit directly
export const APP_VERSION = 'v${newVersion}';
export const BUILD_NUMBER = '${newVersion}';
export const BUILD_TIMESTAMP = '${timestamp}';
export const GIT_COMMIT = '${gitCommit}';
`;

fs.writeFileSync(versionTsPath, content);
console.log(`[Version Bump] Updated to v${newVersion} (${gitCommit})`);
